version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    env_file:
      - .env
    ports:
      - "5005:5005"
    depends_on:
      - postgres
  postgres:
    image: "postgres:9.6.1"
    ports:
       - 5432:5432
    env_file:
      - .env
